-- dws_sale_card_transaction_extend DDL（IF NOT EXISTS，不重建现有表）
CREATE TABLE IF NOT EXISTS public.dws_sale_card_transaction_extend_2024 (
    "id" BIGINT,,
    "account_id" STRING,,
    "sale_or_am_id" STRING,,
    "business_type" STRING,,
    "provider" STRING,,
    "bin" STRING,,
    "status" STRING,,
    "settle_amount" DECIMAL(20,4),,
    "transaction_currency" STRING,,
    "country" STRING,,
    "transaction_count" BIGINT,,
    "fx_fee" DECIMAL(20,4),,
    "atm_fee" DECIMAL(20,4),,
    "apple_pay_fee" DECIMAL(20,4),,
    "settle_fee" DECIMAL(20,4),,
    "create_date" DATE,,
    "version" BIGINT,,
    "create_time" TIMESTAMP(6),,
    "update_time" TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS public.dws_sale_card_transaction_extend_2025 (
    "id" BIGINT,,
    "account_id" STRING,,
    "sale_or_am_id" STRING,,
    "business_type" STRING,,
    "provider" STRING,,
    "bin" STRING,,
    "status" STRING,,
    "settle_amount" DECIMAL(20,4),,
    "transaction_currency" STRING,,
    "country" STRING,,
    "transaction_count" BIGINT,,
    "fx_fee" DECIMAL(20,4),,
    "atm_fee" DECIMAL(20,4),,
    "apple_pay_fee" DECIMAL(20,4),,
    "settle_fee" DECIMAL(20,4),,
    "create_date" DATE,,
    "version" BIGINT,,
    "create_time" TIMESTAMP(6),,
    "update_time" TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS public.dws_sale_card_transaction_extend_2026 (
    "id" BIGINT,,
    "account_id" STRING,,
    "sale_or_am_id" STRING,,
    "business_type" STRING,,
    "provider" STRING,,
    "bin" STRING,,
    "status" STRING,,
    "settle_amount" DECIMAL(20,4),,
    "transaction_currency" STRING,,
    "country" STRING,,
    "transaction_count" BIGINT,,
    "fx_fee" DECIMAL(20,4),,
    "atm_fee" DECIMAL(20,4),,
    "apple_pay_fee" DECIMAL(20,4),,
    "settle_fee" DECIMAL(20,4),,
    "create_date" DATE,,
    "version" BIGINT,,
    "create_time" TIMESTAMP(6),,
    "update_time" TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS public.dws_sale_card_transaction_extend_2027 (
    "id" BIGINT,,
    "account_id" STRING,,
    "sale_or_am_id" STRING,,
    "business_type" STRING,,
    "provider" STRING,,
    "bin" STRING,,
    "status" STRING,,
    "settle_amount" DECIMAL(20,4),,
    "transaction_currency" STRING,,
    "country" STRING,,
    "transaction_count" BIGINT,,
    "fx_fee" DECIMAL(20,4),,
    "atm_fee" DECIMAL(20,4),,
    "apple_pay_fee" DECIMAL(20,4),,
    "settle_fee" DECIMAL(20,4),,
    "create_date" DATE,,
    "version" BIGINT,,
    "create_time" TIMESTAMP(6),,
    "update_time" TIMESTAMP(6)
);
