-- ods_qbit_card DDL（IF NOT EXISTS，不重建现有表）
CREATE TABLE IF NOT EXISTS public.ods_qbit_card_2024 (
    "id" BIGINT,,
    "create_time" TIMESTAMP(6),,
    "update_time" TIMESTAMP(6),,
    "delete_time" TIMESTAMP(6),,
    "version" BIGINT,,
    "remarks" STRING,,
    "card_id" STRING,,
    "account_id" STRING,,
    "currency" STRING,,
    "status" STRING,,
    "provider" STRING,,
    "type" STRING,,
    "token" STRING,,
    "user_delete_time" STRING,,
    "delete_card_time" STRING,,
    "first_six" STRING,,
    "card_belong" STRING,,
    "physical_card_status" STRING,,
    "card_mode" STRING
);

CREATE TABLE IF NOT EXISTS public.ods_qbit_card_2025 (
    "id" BIGINT,,
    "create_time" TIMESTAMP(6),,
    "update_time" TIMESTAMP(6),,
    "delete_time" TIMESTAMP(6),,
    "version" BIGINT,,
    "remarks" STRING,,
    "card_id" STRING,,
    "account_id" STRING,,
    "currency" STRING,,
    "status" STRING,,
    "provider" STRING,,
    "type" STRING,,
    "token" STRING,,
    "user_delete_time" STRING,,
    "delete_card_time" STRING,,
    "first_six" STRING,,
    "card_belong" STRING,,
    "physical_card_status" STRING,,
    "card_mode" STRING
);

CREATE TABLE IF NOT EXISTS public.ods_qbit_card_2026 (
    "id" BIGINT,,
    "create_time" TIMESTAMP(6),,
    "update_time" TIMESTAMP(6),,
    "delete_time" TIMESTAMP(6),,
    "version" BIGINT,,
    "remarks" STRING,,
    "card_id" STRING,,
    "account_id" STRING,,
    "currency" STRING,,
    "status" STRING,,
    "provider" STRING,,
    "type" STRING,,
    "token" STRING,,
    "user_delete_time" STRING,,
    "delete_card_time" STRING,,
    "first_six" STRING,,
    "card_belong" STRING,,
    "physical_card_status" STRING,,
    "card_mode" STRING
);
